name: Resolve Issue with OpenHands

on:
  workflow_dispatch:

  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-openhands-resolver:
    uses: malhotra5/OpenHands/.github/workflows/openhands-resolver.yml@test-environments
    with:
      macro: ${{ vars.AGENT_MACRO || '@openhands-agent' }}
      max_iterations: ${{ vars.OPENHANDS_MAX_ITER || 50 }}
    secrets:
      ENV_SECRETS: ${{ toJSON(secrets) }}
