name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      max_iterations:
        required: true
        type: number
        default: 50
      macro:
        required: true
        type: string
        default: "@openhands-agent"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-openhands-resolver:
    if: |
      github.event.label.name == 'fix-me' ||
      (github.event_name == 'issue_comment' && 
      startsWith(github.event.comment.body, inputs.macro) &&
      (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER'))

    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@bug/comment-invocation
    with:
      max_iterations: ${{ needs.get-env.outputs.MAX_ITERATIONS }}
      macro: ${{ needs.get-env.outputs.MACRO }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
