name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-macro:
    runs-on: ubuntu-latest
    steps:
      - name: Echo macro input
        run: |
          echo "Macro input is: ${{ inputs.macro || '@openhands-agent' }}"

  call-openhands-resolver:
    needs: check-macro
    if: |
      github.event.label.name == 'fix-me' ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@openhands-agent'))
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@bug/comment-invocation
    with:
      max_iterations: 50
      macro: "@custom"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
