name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-macro:
    runs-on: ubuntu-latest
    env:
      MACRO: "@custom"
    steps:
      - name: Set and echo macro input
        run: |
          echo "MACRO=$MACRO" >> $GITHUB_OUTPUT

  call-openhands-resolver:
    needs: check-macro
    if: |
      github.event.label.name == 'fix-me' ||
      (github.event_name == 'issue_comment' && 
      startsWith(github.event.comment.body, needs.check-macro.outputs.MACRO) &&
      (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER'))
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@bug/macro-invocation
    with:
      max_iterations: 50
      macro: needs.check-macro.outputs.MACRO
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
