name: test pr comments
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log github variables
      run: |
          echo "Comment ID: ${{ github.event.comment.id }}"
          echo "Issue/PR Number: ${{ github.event.issue.number }}"

