name: test pr comments
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Variables
        run: |
          echo "Comment ID: ${{ github.event.comment.id }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
